---
extends: default

ignore:
  - ".venv/"
  - "schema-library/"
rules:
  new-lines: disable
  comments-indentation: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
